---
- name: Create shared resources directory
  file:
    path: "{{ config_dirs.nifi_registry_external_config }}"
    state: "directory"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy nifi-registry.properties template
  template:
    src: "templates/nifi-registry.properties.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/nifi-registry.properties"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy bootstrap.conf template
  template:
    src: "templates/bootstrap.conf.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/bootstrap.conf"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy authorizers.xml template
  template:
    src: "templates/authorizers.xml.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/authorizers.xml"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy logback.xml template
  template:
    src: "templates/logback.xml.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/logback.xml"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy identity-providers.xml template
  template:
    src: "templates/identity-providers.xml.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/identity-providers.xml"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Copy providers.xml template
  template:
    src: "templates/providers.xml.j2"
    dest: "{{ config_dirs.nifi_registry_home }}/conf/providers.xml"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
